#!/bin/bash
### Yukki Music Bot Installer

pprint (){
	cred='\033[0;31m'
	cgreen='\033[0;32m'
	cyellow='\033[0;33m'
	cblue='\033[0;34m'
	cpurple='\033[0;35m'
	eval "export color='$cpurple'"
	[ ! -z $2 ] && eval "export color=\"\$$2\""
    printf "$color $1"
}

color_reset(){ printf '\033[0;37m';}

yesnoprompt(){
	old_stty_cfg=$(stty -g)
	stty raw -echo ; answer=$(head -c 1)
	stty $old_stty_cfg
	echo "$answer" | grep -iq "^y"
}

update() {
	pprint "\n\nPaket siyahısı yenilənir.. "
	sudo apt update 2>&1 | grep "can be upgraded" &>/dev/null
	if [ $? -eq 0 ]; then
		pprint "Yeniliklər Mövcuddur" "cgreen"
		pprint "\n\nAvtomatik təkmilləşdirmək istəyirsiniz (y/n)?"
		if yesnoprompt; then
			pprint "\n\nPaketlər təkmilləşdirilir.. "
			sudo apt upgrade -y &>/dev/null &&
			pprint "UĞURLU!\n\n" "cgreen" || (pprint "UĞURSUZ.\n\n" "cred"; exit 1)
		else
			echo
		fi
	else
		pprint "ARTIQ GÜNCƏLƏR\n\n" "cgreen"
	fi
}

packages(){
	if ! command -v pip &>/dev/null; then
		pprint "Pip tapılmadı, indi quraşdırılır.. "
		sudo apt install python3-pip -y 2>pypilog.txt 1>/dev/null &&
		pprint "UĞURLU!\n\n" "cgreen" || (pprint "UĞURSUZ.\n\n" "cred"; exit 1)
	fi

	if ! command -v ffmpeg &>/dev/null; then
		pprint "Couldn't found ffmpeg, installing now.. "
		if sudo apt install ffmpeg -y &>/dev/null;then
			pprint "UĞURLU!\n\n" "cgreen"
		else
			pprint "UĞURSUZ.\n\n" "cred"
			pprint "Çıxan Əkbər Music Bot-dan istifadə etmək üçün ffmpeg-i əl ilə quraşdırmalısınız..\n" "cblue"
			exit 1
		fi
	fi

	# Check ffmpeg version and warn user if necessary.
	fv=$(grep -Po 'version (3.*?) ' <<< $(ffmpeg -version)) &&
	pprint "Ffmpeg olduğundan canlı yayımları oynamaq işləməyəcək $fv, canlı yayımlar versiya tərəfindən dəstəklənir 4+.\n" "cblue"
}


node(){
	command -v npm &>/dev/null && return
	pprint "Nodejs və Npm quraşdırılması..  "
	curl -fssL https://deb.nodesource.com/setup_18.x | sudo -E bash - &>nodelog.txt &&
	sudo apt install nodejs -y &>>nodelog.txt &&
	sudo npm i -g npm &>>nodelog.txt &&
	pprint "UĞURLU!\n" "cgreen" || (pprint "UĞURSUZ.\n" "cred"; exit 1)
}



installation(){
	pprint "\n\nPip-in təkmilləşdirilməsi və asılılıq paketlərinin quraşdırılması.. "
	pip3 install -U pip &>>pypilog.txt &&
	pip3 install -U -r requirements.txt &>>pypilog.txt &&
	pprint "BİTİRİLDİ.\n" "cgreen" && return
	pprint "UĞURSUZ.\n" "cred"
	exit 1
}

clear
pprint "Əkbər Musiqi Bot Quraşdırma Quraşdırıcısına xoş gəlmisiniz\n\n"
pprint "Quraşdırma Prosesi zamanı hər hansı bir səhv görsəniz, qeydlər üçün bu fayllara müraciət edin: "
pprint "\nNode js xətaları üçün , Yoxla nodelog.txt"
pprint "\nPypi paketləri xətaları üçün , Yoxla pypilog.txt"
sleep 2
pprint "\n\nPaketləri yeniləmək və quraşdırmaq üçün skriptə sudo imtiyazları lazımdır.\n"
sudo test

update
packages
node
repo
installation
pprint "\n\n\n\n\nƏkbər Musiqi Botunun quraşdırılması tamamlandı!" "cgreen"
sleep 4
clear

pprint "\nDəyərlərinizi Aşağıya Daxil Edin\n\n\n"
pprint "API ID: "; color_reset; read api_id
pprint "\nAPI HASH: "; color_reset; read api_hash
pprint "\nBOT TOKEN: "; color_reset; read bot_token
pprint "\nMONGO DB URI: "; color_reset; read mongo_db
pprint "\nLOG GROUP ID: "; color_reset; read logger
pprint "\nKÖMƏKÇİ HESABININ PİROQRAM STRING SESSİYASI: "; color_reset; read string_session
pprint "\nMUSIC BOT NAME: "; color_reset; read mbt
pprint "\nOWNER ID:"; color_reset; read ownid

pprint "\n\nVarlarınız emal olunur, bir az gözləyin!" "cgreen"

if [ -f .env ]; then
	rm .env
fi

echo """API_ID = $api_id
API_HASH = $api_hash
BOT_TOKEN = $bot_token
MONGO_DB_URI = $mongo_db
LOG_GROUP_ID = $logger
MUSIC_BOT_NAME = $mbt
STRING_SESSION = $string_session
OWNER_ID = $ownid""" > .env
clear
pprint "\n\n\nVarlarınız Uğurla saxlandı!, Yukki Installer istifadə etdiyiniz üçün təşəkkür edirik, indi siz botu bash start ilə işə salmaqla davam edə bilərsiniz!"
pprint "\n\n\nDaha çox var istəyirsiniz?"
pprint "\nƏlavə variantlar üçün konfiqurasiya qovluğunda config.py və README.md daxil olun. Siz bütün şəkilləri, miniatürləri, rejimi və hər şeyi dəyişə bilərsiniz. Onlara bir nəzər salın.\n\n"
